includes:
  - eureka-client.yml

server:
  port: 8020

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  web:
    resources:
      static-locations: file:storage/images
  mvc:
    static-path-pattern: /resources/images/**
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: team-wave-group-file-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            key:
              default:
                type: org.apache.kafka.common.serialization.StringDeserializer
            value:
              default:
                type: org.springframework.kafka.support.serializer.JsonDeserializer
            trusted:
              packages: "*"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

storage:
  location: file:storage
  images: file:images
  musics: file:musics
  clips: file:clips
  maxImageFileSize: 1048576 # 1MB

secret:
  private:
    key: file:id_rsa
  public:
    key: file:id_rsa.pub