includes:
  - eureka-client.yml

server:
  port: 8002

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5402/location_service_team_wave
    username: manuelisaac
    password: manuelisaac
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        default_schema: PUBLIC

secret:
  private:
    key: file:id_rsa
  public:
    key: file:id_rsa.pub